from django.core.management.base import BaseCommand
from apps.forge.models import ZoneCode 

class Command(BaseCommand):
    help = 'Initialize ZoneCode data'

    def handle(self, *args, **options):
        zone_codes = [
            ("XXX", "全區域(包括機場與建築物)/All zones (This will include site and building)"),
            ("MXX", "多功能大樓/ Multi-Functional Building(MFB)"),
            ("MF1", "多功能大樓/ MFB line W6- line W24"),
            ("MF2", "多功能大樓/ MFB line 63- line W24"),
            ("MF3", "多功能大樓/ MFB line 66 - line 70"),
            ("MX1", "基礎工程/ Foundation (FDN)"),
            ("MX2", "多功能大樓人行通道，並通向第二航廈及多功能大樓之各項設施 /The MFB Walkway With Access To T2 And The MFB Facilities"),
            ("MX3", "建築、結構與屋頂/Building+Structure + Roof"),
            ("MPX", "多功能大樓停車場(P4停車場) /MFB Parking(P4) (Don’t not include parking including in MFB East)"),
            ("MP1", "…"),
            ("MP2", "…."),
            ("MEX", "東側多功能大樓/Multi-Functional Building East (MBE)"),
            ("ME1", "團體報到區/Group Check-in for T2"),
            ("ME2", "停車場(東側多功能大樓)Parking Part of (MFB East)(停用)"),
            ("MCX", "多功能大樓商業區域/Multi-Functional Building Commercial"),
            ("MC1", "綜合商業區域/Commercial Complexes"),
            ("MC2", "人行通道(及零售) /Walkway (and Retail)"),
            ("MH1", "陸側旅館 /The Landside Hotel"),
            ("MH2", "旅館/Hotel"),
            ("MHV", "觀景台/Visitor Viewing Deck"),
            ("MGX", "機房/Plantrooms"),
            ("MOX", "辦公室/Office"),
            ("T2X", "第二航站區界面/Terminal 2 interfaces"),
            ("TXX", "第三航站區/ Terminal 3"),
            ("TX1", "基礎工程/ Foundation (FDN)"),
            ("TX2", "建築、結構與屋頂/Building+Structure + Roof"),
            ("TX3", "建築包覆層(包覆版)/Cladding"),
            ("TX4", "垂直電梯間/Vertical Circulation Cores"),
            ("TX5", "登機門等候區/ Gate Waiting Areas"),
            ("TX6", "空橋系統/ Boarding Bridge System, (PBB)"),
            ("TCX", "報到大廳/Check-in Hall"),
            ("TGX", "機房/Plantrooms"),
            ("THX", "行李提領/Baggage reclaim"),
            ("TRX", "零售中心/Retail Hub"),
            ("TLX", "航廈連接橋/Terminal Link Bridges"),
            ("TTX", "轉機設施/Terminal Transport"),
            ("TT1", "接駁公車/Remote bus"),
            ("TT2", "PMS車站/PMS Station"),
            ("TT3", "APM車站/APM Station"),
            ("TDX", "路緣、陡坡/Curbs, drop-offs"),
            ("TR1", "出境路緣/ Departure Curb"),
            ("TR2", "入境路緣/The Arrival Curb"),
            ("TOX", "航廈辦公區包括/Terminal offices includes : 人員工作區 / Staff workshops ;航空公司辦公室/Airline Offices"),
            ("TPX", "機房/Plantrooms"),
            ("TSX", "政府管制 / Governmental Control; 出境管制 /Immigration Control ;入境管制/ Immigration Control ;安檢掃描/ Security Screening ;海關掃描/ Customs Screening;疾病管制等/ Health Control;護照查驗/Passport Control"),
            ("TMX", "捷運車站/MRT Station ( Include Interface)"),
            ("TBX", "行李處理系統/ Baggage Handling System"),
            ("CXX", "登機廊廳/Concourse"),
            ("CNX", "北登機廳/North Concourse"),
            ("CSX", "南登機廳/South Concourse"),
            ("CS1", "基礎工程/ Foundation (FDN)"),
            ("CS2", "建築、結構與屋頂/Building+Structure + Roof"),
            ("CS3", "建築包覆層(包覆版)/Cladding"),
            ("CS4", "垂直動線/Vertical Circulation Cores"),
            ("CS5", "登機門等候區/Gate waiting areas concourses"),
            ("CS6", "空橋系統/ Boarding Bridge System, (PBB)"),
            ("CS7", "登機廊廳的商業區/Commercial areas at concourses"),
            ("CS8,9", "BOH (Services, Offices, Others)"),
            ("LXX", "陸側/Landside"),
            ("L01", "土方工程/ Earthwork"),
            ("L02", "地下共同管道/Underground Utility Corridor"),
            ("LAX", "航站南北路/ Access rosd (HZ N&S)"),
            ("LAN", "航站北路/ Access rosd (HZ N)"),
            ("LAS", "航站南路/ Access rosd (HZ S)"),
            ("LSX", "地下滯洪設施/Storm Retention System"),
            ("LS1", "DB01 地下滯洪設施/DB01 Storm Retention System"),
            ("LS2", "DB02 地下滯洪設施/DB02 Storm Retention System"),
            ("LS3", "DB03 地下滯洪設施/DB03 Storm Retention System"),
            ("LEX", "能源中心/ Energy Center 移至 AXX 區/Moved to AXX (Airside)"),
            ("LWX", "水處理廠/ Waste Water Treatment Plant 移至 AXX 區/Moved to AXX (Airside)"),
            ("LPX", "自來水儲水加壓站/ Water Storage and Pump Station (WSP) 移至AXX區/Moved to AXX (Airside)"),
            ("AXX", "空側/Airside"),
            ("A01", "遷建之WC跨場滑行道/Relocated WC Cross Taxiway"),
            ("A02", "連接西側的進場道路/Access Road from West"),
            ("A03", "通往西側的出場道路/Exit Road to the West"),
            ("A04", "既有管線遷移/ Existing Utility Relocation"),
            ("A05", "西側變電站/ West 161kv Electrical Sub-Station (ESS)"),
            ("A06", "南側變電站/ South 161kv Electrical Sub-Station (ESS)"),
            ("A07", "地下共同管道 / Underground Utility Corridor, part of APN construction (UUC)"),
            ("A08", "污 水 及 其 淨 化 後 回 收 水 管 線 系 統 / Waste Water and the Treated/Purified Water Recycle Pipelines Network (Connected to AEX 能源中心/ Energy Center"),
            ("AFS", "消防西站/Fire West Station"),
            ("AWX", "汙水處理廠/ Waste Water Treatment Plant"),
            ("APX", "自來水儲水加壓站/ Water Storage and Pump Station (WSP)"),
            ("APE", "停機坪E /Apron E"),
            ("APF", "停機坪F 與滑行道TWY Q /Apron F and Taxiway Q"),
            ("APG", "停機坪G /Apron G"),
            ("AME", "停機坪E標線/Apron E Marking"),
            ("AMF", "停機坪F標線/Apron F Marking"),
            ("AMG", "停機坪G標線/Apron G Marking"),
            ("ATX", "滑行道 Taxiway"),
            ("ATP", "滑行道 P5 / Taxiway P5"),
            ("ATY", "滑行道Y1 & Y2 / Taxiway Y1 & Y2"),
            ("ATQ", "滑行道Q3 / Taxiway Q3"),
            ("ARX", "勤務道路 / Service Road for Termail 3"),
            ("AR1", "勤務道路"),
            ("AR2", "勤務道路"),
            ("AR3", "勤務道路"),
            ("AR4", "勤務道路"),
            ("AR5", "勤務道路"),
            ("AR6", "勤務道路"),
            ("SRX", "勤務道路 / Service Road for WC Taxiway"),
            ("SR1", "勤務道路"),
            ("SR2", "勤務道路"),
            ("SR3", "勤務道路"),
            ("SR4", "勤務道路"),
        ]

        self.stdout.write(self.style.NOTICE('Initializing ZoneCode...'))
        for code, description in zone_codes:
            obj, created = ZoneCode.objects.update_or_create(
                code=code,
                defaults={'description': description}
            )
            action = "Inserted" if created else "Updated"
            self.stdout.write(self.style.SUCCESS(f"{action} ZoneCode: {code} - {description}"))
        self.stdout.write(self.style.SUCCESS('ZoneCode initialization completed!'))
