from django.core.management.base import BaseCommand
from apps.forge.models import ZoneCode 

class Command(BaseCommand):
    help = 'Initialize ZoneCode data'

    def handle(self, *args, **options):
        zone_codes = [
            ("XXX", "全區域"),
            ("MXX", "多功能大樓"),
            ("MF1", "多功能大樓"),
            ("MF2", "多功能大樓"),
            ("MF3", "多功能大樓"),
            ("MX1", "基礎工程"),
            ("MX2", "多功能大樓人行通道"),
            ("MX3", "建築、結構與屋頂"),
            ("MPX", "多功能大樓停車場"),
            ("MP1", "…"),
            ("MP2", "…."),
            ("MEX", "東側多功能大樓"),
            ("ME1", "團體報到區"),
            ("ME2", "停車場(東側多功能大樓)"),
            ("MCX", "多功能大樓商業區域"),
            ("MC1", "綜合商業區域"),
            ("MC2", "人行通道(及零售)"),
            ("MH1", "陸側旅館"),
            ("MH2", "旅館"),
            ("MHV", "觀景台"),
            ("MGX", "機房"),
            ("MOX", "辦公室"),
            ("T2X", "第二航站區界面"),
            ("TXX", "第三航站區"),
            ("TX1", "基礎工程"),
            ("TX2", "建築、結構與屋頂"),
            ("TX3", "建築包覆層"),
            ("TX4", "垂直電梯間"),
            ("TX5", "登機門等候區"),
            ("TX6", "空橋系統"),
            ("TCX", "報到大廳"),
            ("TGX", "機房"),
            ("THX", "行李提領"),
            ("TRX", "零售中心"),
            ("TLX", "航廈連接橋"),
            ("TTX", "轉機設施"),
            ("TT1", "接駁公車"),
            ("TT2", "PMS車站"),
            ("TT3", "APM車站"),
            ("TDX", "路緣、陡坡"),
            ("TR1", "出境路緣"),
            ("TR2", "入境路緣"),
            ("TOX", "航廈辦公區包括"),
            ("TPX", "機房"),
            ("TSX", "政府管制"),
            ("TMX", "捷運車站"),
            ("TBX", "行李處理系統"),
            ("CXX", "登機廊廳"),
            ("CNX", "北登機廳"),
            ("CSX", "南登機廳"),
            ("CS1", "基礎工程"),
            ("CS2", "建築、結構與屋頂"),
            ("CS3", "建築包覆層(包覆版)"),
            ("CS4", "垂直動線"),
            ("CS5", "登機門等候區"),
            ("CS6", "空橋系統"),
            ("CS7", "登機廊廳的商業區"),
            ("CS8", "BOH"),
            ("CS9", "BOH"),
            ("LXX", "陸側"),
            ("L01", "土方工程"),
            ("L02", "地下共同管道"),
            ("LAX", "航站南北路"),
            ("LAN", "航站北路"),
            ("LAS", "航站南路"),
            ("LSX", "地下滯洪設施"),
            ("LS1", "DB01 地下滯洪設施"),
            ("LS2", "DB02 地下滯洪設施"),
            ("LS3", "DB03 地下滯洪設施"),
            ("LEX", "能源中心"),
            ("LWX", "水處理廠"),
            ("LPX", "自來水儲水加壓站"),
            ("AXX", "空側"),
            ("A01", "遷建之WC跨場滑行道"),
            ("A02", "連接西側的進場道路"),
            ("A03", "通往西側的出場道路"),
            ("A04", "既有管線遷移"),
            ("A05", "西側變電站"),
            ("A06", "南側變電站"),
            ("A07", "地下共同管道"),
            ("A08", "污水及其淨化後回收水管線系統"),
            ("AFS", "消防西站"),
            ("AWX", "汙水處理廠"),
            ("APX", "自來水儲水加壓站"),
            ("APE", "停機坪E"),
            ("APF", "停機坪F"),
            ("APG", "停機坪G"),
            ("AME", "停機坪E標線"),
            ("AMF", "停機坪F標線"),
            ("AMG", "停機坪G標線"),
            ("ATX", "滑行道"),
            ("ATP", "滑行道P5"),
            ("ATY", "滑行道Y1&Y2"),
            ("ATQ", "滑行道Q3"),
            ("ARX", "勤務道路"),
            ("AR1", "勤務道路"),
            ("AR2", "勤務道路"),
            ("AR3", "勤務道路"),
            ("AR4", "勤務道路"),
            ("AR5", "勤務道路"),
            ("AR6", "勤務道路"),
            ("SRX", "勤務道路"),
            ("SR1", "勤務道路"),
            ("SR2", "勤務道路"),
            ("SR3", "勤務道路"),
            ("SR4", "勤務道路"),
        ]

        self.stdout.write(self.style.NOTICE('Initializing ZoneCode...'))
        for code, description in zone_codes:
            obj, created = ZoneCode.objects.update_or_create(
                code=code,
                defaults={'description': description}
            )
            action = "Inserted" if created else "Updated"
            self.stdout.write(self.style.SUCCESS(f"{action} ZoneCode: {code} - {description}"))
        self.stdout.write(self.style.SUCCESS('ZoneCode initialization completed!'))
