# Generated by Django 5.1.4 on 2025-01-21 06:07

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_locale', models.CharField(max_length=30)),
                ('subtitle_locale', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('aside', 'aside'), ('basic', 'basic'), ('collapsable', 'collapsable'), ('divider', 'divider'), ('group', 'group'), ('spacer', 'spacer')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=120, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigation')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'verbose_name_plural': 'Navigations',
                'permissions': [],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locale')),
            ],
            options={
                'unique_together': {('key', 'lang')},
            },
        ),
    ]
