# Generated by Django 5.1.4 on 2025-01-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locale',
            old_name='code',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='lang',
            new_name='locale',
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('key', 'locale')},
        ),
    ]
