# Generated by Django 5.2 on 2025-05-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguseractivity',
            name='action',
            field=models.TextField(verbose_name='執行動作'),
        ),
    ]
