# Generated by Django 5.1.4 on 2025-01-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_code_locale_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
