# Generated by Django 5.1.4 on 2025-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_autodeskcredentials_bucket_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskcredentials',
            name='bucket_key',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
