# Generated by Django 5.1.4 on 2025-03-10 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apscredentials_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_function', models.CharField(max_length=255, verbose_name='系統功能名稱')),
                ('action', models.CharField(max_length=255, verbose_name='執行動作')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='執行時間')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail')], default='SUCCESS', max_length=10, verbose_name='狀態')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者帳號')),
            ],
        ),
    ]
