# Generated by Django 5.2 on 2025-05-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_loguseractivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bim_criteria',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
