# Generated by Django 5.1.4 on 2025-02-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autodeskcredentials_bucket_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskcredentials',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='autodeskcredentials',
            name='client_secret',
            field=models.CharField(max_length=255),
        ),
    ]
