# Generated by Django 5.1.4 on 2025-03-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loguseractivity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loguseractivity',
            table='core_log_user_activity',
        ),
    ]
