# Generated by Django 5.1.4 on 2025-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_bim_criteria'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['key', 'locale_id'], name='core_transl_key_005785_idx'),
        ),
    ]
