# Generated by Django 5.1.4 on 2025-02-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_autodeskcredentials_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskcredentials',
            name='bucket_key',
        ),
    ]
