# Generated by Django 5.1.4 on 2025-03-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_loguseractivity_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loguseractivity',
            old_name='system_function',
            new_name='function',
        ),
    ]
