# Generated by Django 5.1.4 on 2025-02-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_autodeskcredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodeskcredentials',
            old_name='_client_secret',
            new_name='client_secret',
        ),
    ]
