# Generated by Django 5.1.4 on 2025-02-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_autodeskcredentials_bucket_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutodeskCredentials',
            new_name='ApsCredentials',
        ),
    ]
