# Generated by Django 5.1.4 on 2025-04-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BimGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forge_bim_type',
                'indexes': [models.Index(fields=['display_name'], name='forge_bim_t_display_e86d65_idx'), models.Index(fields=['value'], name='forge_bim_t_value_b84de3_idx')],
            },
        ),
        migrations.CreateModel(
            name='BimGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('types', models.ManyToManyField(blank=True, related_name='bim_groups', to='forge.bimgrouptype')),
            ],
            options={
                'db_table': 'forge_bim_group',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('urn', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forge_bim_model',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='forge_bim_m_name_a6fce3_idx')],
            },
        ),
        migrations.CreateModel(
            name='BimCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('bim_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimgroup')),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimmodel')),
            ],
            options={
                'verbose_name_plural': 'Bim categories',
                'db_table': 'forge_bim_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BimObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.IntegerField()),
                ('primary_value', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_objects', to='forge.bimcategory')),
            ],
            options={
                'db_table': 'forge_bim_object',
            },
        ),
        migrations.AddIndex(
            model_name='bimgroup',
            index=models.Index(fields=['name'], name='forge_bim_g_name_da7257_idx'),
        ),
        migrations.AddIndex(
            model_name='bimgroup',
            index=models.Index(fields=['order'], name='forge_bim_g_order_af5f40_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['bim_group'], name='forge_bim_c_bim_gro_eefa4d_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['value'], name='forge_bim_c_value_ed5b2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('bim_model', 'bim_group', 'value')},
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['category'], name='forge_bim_o_categor_7d2372_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['dbid'], name='forge_bim_o_dbid_0fbf8a_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['dbid', 'category'], name='forge_bim_o_dbid_59041f_idx'),
        ),
    ]
