# Generated by Django 5.1.4 on 2025-02-15 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BimCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'forge_bim_category',
            },
        ),
        migrations.CreateModel(
            name='BimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forge_bim_model',
            },
        ),
        migrations.CreateModel(
            name='BimConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('original_file', models.CharField(max_length=500)),
                ('svf_file', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='forge.bimmodel')),
            ],
            options={
                'db_table': 'forge_bim_conversion',
                'unique_together': {('bim_model', 'version')},
            },
        ),
    ]
