# Generated by Django 5.1.4 on 2025-02-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BIMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=255, unique=True)),
                ('version', models.IntegerField()),
                ('original_file', models.FileField(upload_to='bim_models/')),
                ('svf_file', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='forge.bimmodel')),
            ],
            options={
                'unique_together': {('bim_model', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BIMObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bim_conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_objects', to='forge.bimconversion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_objects', to='forge.category')),
            ],
        ),
        migrations.CreateModel(
            name='BIMProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('bim_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='forge.bimobject')),
            ],
        ),
    ]
