# Generated by Django 5.1.4 on 2025-04-09 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'forge_zone_code',
            },
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='zone_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_models', to='forge.zonecode'),
        ),
    ]
