# Generated by Django 5.1.4 on 2025-02-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='bimconversion',
            name='original_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bimconversion',
            name='svf_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bimconversion',
            name='urn',
            field=models.CharField(max_length=255),
        ),
    ]
