# Generated by Django 5.1.4 on 2025-02-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0003_bimmodel_tender_tender_level_tender_lft_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tender',
            new_name='BimTender',
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
