# Generated by Django 5.1.4 on 2025-04-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0003_levelcode_alter_bimmodel_zone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimmodel',
            name='level_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bim_models_level', to='forge.levelcode'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='zone_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bim_models', to='forge.zonecode'),
        ),
    ]
