# Generated by Django 5.1.4 on 2025-02-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0004_rename_tender_bimtender_bimcategory_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bimtender',
            table='forge_bim_tender',
        ),
    ]
