# Generated by Django 5.1.4 on 2025-04-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0004_alter_bimmodel_level_code_alter_bimmodel_zone_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bimobject',
            name='forge_bim_o_categor_7d2372_idx',
        ),
        migrations.RemoveIndex(
            model_name='bimobject',
            name='forge_bim_o_dbid_59041f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('bim_group', 'value')},
        ),
        migrations.RemoveField(
            model_name='bimobject',
            name='category',
        ),
        migrations.AddField(
            model_name='bimobject',
            name='bim_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimmodel'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['bim_model'], name='forge_bim_o_bim_mod_ceae9e_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['display_name'], name='forge_bim_o_display_5962dc_idx'),
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='bim_model',
        ),
    ]
