# Generated by Django 5.1.4 on 2025-02-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0005_alter_bimtender_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimcategory',
            options={'verbose_name_plural': 'Bim categories'},
        ),
    ]
