# Generated by Django 5.1.4 on 2025-04-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0005_remove_bimobject_forge_bim_o_categor_7d2372_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimobject',
            name='primary_value',
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['value'], name='forge_bim_o_value_a4220c_idx'),
        ),
        migrations.AddIndex(
            model_name='levelcode',
            index=models.Index(fields=['code'], name='forge_level_code_b5e99b_idx'),
        ),
        migrations.AddIndex(
            model_name='zonecode',
            index=models.Index(fields=['code'], name='forge_zone__code_afcbf9_idx'),
        ),
    ]
