# Generated by Django 5.1.4 on 2025-02-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0006_alter_bimcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimmodel',
            name='tender',
        ),
        migrations.DeleteModel(
            name='BimTender',
        ),
    ]
