# Generated by Django 5.1.4 on 2025-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0006_remove_bimobject_primary_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimmodel',
            name='last_processed_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
