# Generated by Django 5.1.4 on 2025-02-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0007_remove_bimmodel_tender_delete_bimtender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'BIM groups',
                'db_table': 'forge_bim_group',
            },
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='bim_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_category', to='forge.bimgroup'),
        ),
    ]
