# Generated by Django 5.1.4 on 2025-04-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0007_bimmodel_last_processed_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimobject',
            name='bim_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_objects', to='forge.bimmodel'),
        ),
    ]
