# Generated by Django 5.1.4 on 2025-04-17 10:30

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0008_alter_bimobject_bim_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'db_table': 'forge_filter_condition',
            },
        ),
        migrations.CreateModel(
            name='FilterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'forge_filter_set',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='bimgroup',
            name='types',
        ),
        migrations.RemoveIndex(
            model_name='bimcategory',
            name='forge_bim_c_bim_gro_eefa4d_idx',
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='bim_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filtercondition',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forge.filtercondition'),
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='filter_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.filtercondition'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='filterset',
            index=models.Index(fields=['name'], name='forge_filte_name_90410d_idx'),
        ),
        migrations.AddIndex(
            model_name='filterset',
            index=models.Index(fields=['order'], name='forge_filte_order_76ca3f_idx'),
        ),
        migrations.AddField(
            model_name='filtercondition',
            name='filter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='forge.filterset'),
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='filter_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.filterset'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('filter_set', 'filter_condition', 'value')},
        ),
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['filter_set'], name='forge_bim_c_filter__f9c2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['filter_condition'], name='forge_bim_c_filter__c66348_idx'),
        ),
        migrations.DeleteModel(
            name='BimGroupType',
        ),
        migrations.AddIndex(
            model_name='filtercondition',
            index=models.Index(fields=['display_name'], name='forge_filte_display_00db60_idx'),
        ),
        migrations.AddIndex(
            model_name='filtercondition',
            index=models.Index(fields=['value'], name='forge_filte_value_c25b49_idx'),
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='bim_group',
        ),
        migrations.DeleteModel(
            name='BimGroup',
        ),
    ]
