# Generated by Django 5.1.4 on 2025-02-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0008_bimgroup_bimcategory_bim_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimgroup',
            options={},
        ),
    ]
