# Generated by Django 5.1.4 on 2025-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0009_alter_bimgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimgroup',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
