# Generated by Django 5.1.4 on 2025-04-17 12:28

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0009_filtercondition_filterset_remove_bimgroup_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'db_table': 'forge_bim_condition',
            },
        ),
        migrations.RemoveField(
            model_name='filtercondition',
            name='filter_set',
        ),
        migrations.RemoveField(
            model_name='filtercondition',
            name='parent',
        ),
        migrations.RemoveIndex(
            model_name='bimcategory',
            name='forge_bim_c_filter__f9c2a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='bimcategory',
            name='forge_bim_c_filter__c66348_idx',
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forge.bimcategory'),
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bimcategory',
            name='bim_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='forge.bimmodel'),
        ),
        migrations.AddField(
            model_name='bimcondition',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forge.bimcondition'),
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='forge.bimcondition'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('bim_model', 'condition', 'value')},
        ),
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['bim_model'], name='forge_bim_c_bim_mod_2a06ed_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['condition'], name='forge_bim_c_conditi_96d3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcondition',
            index=models.Index(fields=['name'], name='forge_bim_c_name_a8967f_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcondition',
            index=models.Index(fields=['display_name'], name='forge_bim_c_display_6ba5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcondition',
            index=models.Index(fields=['value'], name='forge_bim_c_value_fbe81e_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcondition',
            index=models.Index(fields=['order'], name='forge_bim_c_order_87915f_idx'),
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='filter_condition',
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='filter_set',
        ),
        migrations.DeleteModel(
            name='FilterCondition',
        ),
        migrations.DeleteModel(
            name='FilterSet',
        ),
    ]
