# Generated by Django 5.1.4 on 2025-02-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0010_bimgroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimcategory',
            name='bim_group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_category', to='forge.bimgroup'),
        ),
    ]
