# Generated by Django 5.1.4 on 2025-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0010_bimcondition_remove_filtercondition_filter_set_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bimcategory',
            name='forge_bim_c_bim_mod_2a06ed_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('condition', 'value')},
        ),
        migrations.AlterField(
            model_name='bimcondition',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='bim_model',
        ),
    ]
