# Generated by Django 5.1.4 on 2025-02-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0011_alter_bimcategory_bim_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimcategory',
            options={'ordering': ['id'], 'verbose_name_plural': 'Bim categories'},
        ),
        migrations.AlterModelOptions(
            name='bimconversion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bimgroup',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bimmodel',
            options={'ordering': ['id']},
        ),
    ]
