# Generated by Django 5.1.4 on 2025-04-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0011_remove_bimcategory_forge_bim_c_bim_mod_2a06ed_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimcategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='tree_id',
        ),
    ]
