# Generated by Django 5.1.4 on 2025-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0012_remove_bimcategory_level_remove_bimcategory_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimcondition',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
