# Generated by Django 5.1.4 on 2025-02-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0012_alter_bimcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimcategory',
            name='bim_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_category', to='forge.bimgroup'),
        ),
    ]
