# Generated by Django 5.1.4 on 2025-02-18 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0013_alter_bimcategory_bim_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIMProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('bim_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_properties', to='forge.bimconversion')),
            ],
        ),
    ]
