# Generated by Django 5.1.4 on 2025-04-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0013_alter_bimcondition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimcategory',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimcondition'),
        ),
    ]
