# Generated by Django 5.1.4 on 2025-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0014_alter_bimcategory_condition'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimcondition',
            index=models.Index(fields=['parent_id'], name='forge_bim_c_parent__466d97_idx'),
        ),
    ]
