# Generated by Django 5.1.4 on 2025-02-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0014_bimproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimproperty',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bim_category', to='forge.bimconversion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bimproperty',
            name='bim_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_property', to='forge.bimconversion'),
        ),
        migrations.AlterField(
            model_name='bimproperty',
            name='dbid',
            field=models.IntegerField(),
        ),
    ]
