# Generated by Django 5.2 on 2025-04-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0015_bimcondition_forge_bim_c_parent__466d97_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimcategory',
            name='bim_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimmodel'),
        ),
    ]
