# Generated by Django 5.1.4 on 2025-02-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0015_bimproperty_category_alter_bimproperty_bim_object_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimproperty',
            old_name='bim_object',
            new_name='conversion',
        ),
        migrations.AlterField(
            model_name='bimconversion',
            name='bim_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_conversions', to='forge.bimmodel'),
        ),
        migrations.AlterField(
            model_name='bimproperty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_property', to='forge.bimcategory'),
        ),
        migrations.AlterField(
            model_name='bimproperty',
            name='dbid',
            field=models.IntegerField(unique=True),
        ),
    ]
