# Generated by Django 5.2 on 2025-04-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0016_bimcategory_bim_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimcategory',
            name='bim_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimmodel'),
        ),
    ]
