# Generated by Django 5.1.4 on 2025-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0016_rename_bim_object_bimproperty_conversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimproperty',
            name='dbid',
            field=models.IntegerField(),
        ),
    ]
