# Generated by Django 5.2 on 2025-04-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0017_alter_bimcategory_bim_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('bim_model', 'condition', 'value')},
        ),
    ]
