# Generated by Django 5.1.4 on 2025-02-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0017_alter_bimproperty_dbid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bimproperty',
            table='forge_bim_property',
        ),
    ]
