# Generated by Django 5.2 on 2025-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0018_alter_bimcategory_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['display_name', 'value'], name='forge_bim_c_display_7feb06_idx'),
        ),
    ]
