# Generated by Django 5.1.4 on 2025-02-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0018_alter_bimproperty_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimproperty',
            old_name='name',
            new_name='key',
        ),
    ]
