# Generated by Django 5.1.4 on 2025-03-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0019_rename_name_bimproperty_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimgroup',
            name='cobie',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
