# Generated by Django 5.2 on 2025-04-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0019_bimcategory_forge_bim_c_display_7feb06_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['display_name', 'value'], name='forge_bim_o_display_db1e96_idx'),
        ),
    ]
