# Generated by Django 5.1.4 on 2025-03-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0020_bimgroup_cobie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
