# Generated by Django 5.2 on 2025-04-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0020_bimobject_forge_bim_o_display_db1e96_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimmodel',
            name='level_code',
        ),
        migrations.DeleteModel(
            name='LevelCode',
        ),
    ]
