# Generated by Django 5.1.4 on 2025-03-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0021_bimgroup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
