# Generated by Django 5.2 on 2025-04-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0021_remove_bimmodel_level_code_delete_levelcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('dbid', models.IntegerField()),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_zones', to='forge.bimmodel')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bim_zones', to='forge.zonecode')),
            ],
            options={
                'verbose_name_plural': 'Bim zones',
                'db_table': 'forge_bim_zone',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['bim_model'], name='forge_bim_z_bim_mod_abc745_idx'), models.Index(fields=['zone'], name='forge_bim_z_zone_id_a560fe_idx'), models.Index(fields=['level'], name='forge_bim_z_level_1b22f9_idx')],
                'unique_together': {('bim_model', 'zone', 'level', 'dbid')},
            },
        ),
    ]
