# Generated by Django 5.1.4 on 2025-03-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0022_alter_bimcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forge_bim_group_type',
            },
        ),
        migrations.AddField(
            model_name='bimgroup',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bim_group', to='forge.bimgrouptype'),
            preserve_default=False,
        ),
    ]
