# Generated by Django 5.2 on 2025-04-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0022_bimzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimNodeHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_hierarchies', to='forge.bimmodel')),
            ],
            options={
                'db_table': 'forge_bim_node_hierarchy',
                'indexes': [models.Index(fields=['bim_model'], name='forge_bim_n_bim_mod_69a568_idx'), models.Index(fields=['entity_id'], name='forge_bim_n_entity__cf4f20_idx'), models.Index(fields=['parent_id'], name='forge_bim_n_parent__46f851_idx')],
                'unique_together': {('bim_model', 'entity_id')},
            },
        ),
    ]
