# Generated by Django 5.2 on 2025-04-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0023_bimnodehierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimObjectHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_hierarchies', to='forge.bimmodel')),
            ],
            options={
                'db_table': 'forge_bim_object_hierarchy',
            },
        ),
        migrations.DeleteModel(
            name='BimNodeHierarchy',
        ),
        migrations.AddIndex(
            model_name='bimobjecthierarchy',
            index=models.Index(fields=['bim_model'], name='forge_bim_o_bim_mod_9b0f82_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobjecthierarchy',
            index=models.Index(fields=['entity_id'], name='forge_bim_o_entity__d1ab11_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobjecthierarchy',
            index=models.Index(fields=['parent_id'], name='forge_bim_o_parent__6da1f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bimobjecthierarchy',
            unique_together={('bim_model', 'entity_id')},
        ),
    ]
