# Generated by Django 5.1.4 on 2025-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0023_bimgrouptype_bimgroup_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimgroup',
            name='type',
        ),
        migrations.AddField(
            model_name='bimgroup',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='bim_groups', to='forge.bimgrouptype'),
        ),
    ]
