# Generated by Django 5.2 on 2025-04-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0024_bimobjecthierarchy_delete_bimnodehierarchy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('dbid', models.IntegerField()),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_regions', to='forge.bimmodel')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bim_regions', to='forge.zonecode')),
            ],
            options={
                'verbose_name_plural': 'Bim zones',
                'db_table': 'forge_bim_region',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='BimZone',
        ),
        migrations.AddIndex(
            model_name='bimregion',
            index=models.Index(fields=['bim_model'], name='forge_bim_r_bim_mod_bbded3_idx'),
        ),
        migrations.AddIndex(
            model_name='bimregion',
            index=models.Index(fields=['zone'], name='forge_bim_r_zone_id_cdb1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='bimregion',
            index=models.Index(fields=['level'], name='forge_bim_r_level_2ee72a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bimregion',
            unique_together={('bim_model', 'zone', 'level', 'dbid')},
        ),
    ]
