# Generated by Django 5.1.4 on 2025-03-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0024_remove_bimgroup_type_bimgroup_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimmodel',
            options={},
        ),
    ]
