# Generated by Django 5.1.4 on 2025-03-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0025_alter_bimmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimmodel',
            options={'ordering': ['id']},
        ),
    ]
