# Generated by Django 5.2 on 2025-04-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0025_bimregion_delete_bimzone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimregion',
            options={'ordering': ['id'], 'verbose_name_plural': 'Bim regions'},
        ),
    ]
