# Generated by Django 5.1.4 on 2025-03-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0026_alter_bimmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimgroup',
            name='cobie',
        ),
        migrations.RemoveField(
            model_name='bimgroup',
            name='types',
        ),
        migrations.AddField(
            model_name='bimgroup',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_group', to='forge.bimgrouptype'),
        ),
    ]
