# Generated by Django 5.2 on 2025-04-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0026_alter_bimregion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimmodel',
            name='zone_code',
        ),
    ]
