# Generated by Django 5.1.4 on 2025-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0027_remove_bimgroup_cobie_remove_bimgroup_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
