# Generated by Django 5.2 on 2025-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0027_remove_bimmodel_zone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
