# Generated by Django 5.1.4 on 2025-03-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0028_bimmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimmodel',
            name='description',
        ),
    ]
