# Generated by Django 5.2 on 2025-04-24 08:23

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0028_zonecode_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bimobject',
            name='forge_bim_o_display_db1e96_idx',
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['bim_model', 'dbid', 'value'], name='forge_bim_o_bim_mod_db7592_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['value'], name='idx_bim_obj_val_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='bimobjecthierarchy',
            index=models.Index(fields=['bim_model', 'parent_id'], name='forge_bim_o_bim_mod_7e68cc_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobjecthierarchy',
            index=models.Index(fields=['parent_id', 'entity_id'], name='forge_bim_o_parent__9aa346_idx'),
        ),
    ]
