# Generated by Django 5.2 on 2025-05-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0029_remove_bimobject_forge_bim_o_display_db1e96_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bimobjecthierarchy',
            name='forge_bim_o_bim_mod_9b0f82_idx',
        ),
        migrations.RemoveIndex(
            model_name='bimobjecthierarchy',
            name='forge_bim_o_parent__6da1f2_idx',
        ),
    ]
