# Generated by Django 5.1.4 on 2025-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0029_remove_bimmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimgroup',
            name='type',
        ),
        migrations.AddField(
            model_name='bimgroup',
            name='cobie',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimgroup',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='bim_groups', to='forge.bimgrouptype'),
        ),
    ]
