# Generated by Django 5.2 on 2025-05-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0030_remove_bimobjecthierarchy_forge_bim_o_bim_mod_9b0f82_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimcategory',
            name='is_active',
        ),
    ]
