# Generated by Django 5.1.4 on 2025-03-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0030_remove_bimgroup_type_bimgroup_cobie_bimgroup_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimgroup',
            name='cobie',
        ),
    ]
