# Generated by Django 5.1.4 on 2025-03-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0031_remove_bimgroup_cobie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BIMProperty',
            new_name='BimObject',
        ),
        migrations.RenameField(
            model_name='bimgrouptype',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AlterModelTable(
            name='bimobject',
            table='forge_bim_object',
        ),
    ]
