# Generated by Django 5.2 on 2025-05-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0031_remove_bimcategory_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonecode',
            name='is_active',
        ),
    ]
