# Generated by Django 5.2 on 2025-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0032_remove_zonecode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimmodel',
            name='svf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
