# Generated by Django 5.1.4 on 2025-03-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0032_rename_bimproperty_bimobject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimobject',
            old_name='key',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='bimobject',
            unique_together={('conversion', 'dbid')},
        ),
        migrations.AddField(
            model_name='bimobject',
            name='is_leaf',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bimcategory',
            name='bim_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimgroup'),
        ),
        migrations.AlterField(
            model_name='bimobject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_objects', to='forge.bimcategory'),
        ),
        migrations.AlterField(
            model_name='bimobject',
            name='conversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_objects', to='forge.bimconversion'),
        ),
        migrations.RemoveField(
            model_name='bimobject',
            name='value',
        ),
    ]
