# Generated by Django 5.2 on 2025-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0033_bimmodel_svf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimmodel',
            name='sqlite_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
