# Generated by Django 5.1.4 on 2025-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0033_rename_key_bimobject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimobject',
            name='child_dbids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bimobject',
            name='parent_dbid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
