# Generated by Django 5.1.4 on 2025-03-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0034_bimobject_child_dbids_bimobject_parent_dbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimcategory',
            old_name='description',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='bimcategory',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='bimobject',
            old_name='child_dbids',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='bimobject',
            old_name='parent_dbid',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='bimobject',
            old_name='name',
            new_name='value',
        ),
    ]
