# Generated by Django 5.1.4 on 2025-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0034_bimmodel_sqlite_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'forge_role_code',
                'indexes': [models.Index(fields=['code'], name='forge_role__code_36b8a6_idx')],
            },
        ),
    ]
