# Generated by Django 5.1.4 on 2025-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0035_rename_description_bimcategory_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimobject',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
