# Generated by Django 5.1.4 on 2025-06-06 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0035_rolecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimregion',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bim_regions', to='forge.rolecode'),
        ),
    ]
