# Generated by Django 5.1.4 on 2025-03-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0036_bimobject_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimgrouptype',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
