# Generated by Django 5.1.4 on 2025-06-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0036_bimregion_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bimregion',
            unique_together={('bim_model', 'zone', 'role', 'level', 'dbid')},
        ),
    ]
