# Generated by Django 5.1.4 on 2025-06-06 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0037_alter_bimregion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimregion',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bim_regions', to='forge.zonecode'),
        ),
    ]
