# Generated by Django 5.1.4 on 2025-03-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0037_bimgrouptype_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bimobject',
            unique_together=set(),
        ),
    ]
