# Generated by Django 5.1.4 on 2025-03-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0038_alter_bimobject_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimobject',
            name='child',
        ),
        migrations.RemoveField(
            model_name='bimobject',
            name='is_leaf',
        ),
        migrations.RemoveField(
            model_name='bimobject',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='bimobject',
            name='parent_name',
        ),
    ]
