# Generated by Django 5.1.4 on 2025-06-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0038_alter_bimregion_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimregion',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_regions', to='forge.rolecode'),
        ),
        migrations.AlterField(
            model_name='bimregion',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_regions', to='forge.zonecode'),
        ),
    ]
