# Generated by Django 5.1.4 on 2025-06-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0039_alter_bimregion_role_alter_bimregion_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimobject',
            name='root_dbid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['root_dbid'], name='forge_bim_o_root_db_dc80ae_idx'),
        ),
    ]
