# Generated by Django 5.1.4 on 2025-03-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0039_remove_bimobject_child_remove_bimobject_is_leaf_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['bim_group'], name='forge_bim_c_bim_gro_eefa4d_idx'),
        ),
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['value'], name='forge_bim_c_value_ed5b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='bimconversion',
            index=models.Index(fields=['bim_model'], name='forge_bim_c_bim_mod_24512d_idx'),
        ),
        migrations.AddIndex(
            model_name='bimconversion',
            index=models.Index(fields=['version'], name='forge_bim_c_version_9a010c_idx'),
        ),
        migrations.AddIndex(
            model_name='bimconversion',
            index=models.Index(fields=['urn'], name='forge_bim_c_urn_0effe3_idx'),
        ),
        migrations.AddIndex(
            model_name='bimgroup',
            index=models.Index(fields=['name'], name='forge_bim_g_name_da7257_idx'),
        ),
        migrations.AddIndex(
            model_name='bimgroup',
            index=models.Index(fields=['order'], name='forge_bim_g_order_af5f40_idx'),
        ),
        migrations.AddIndex(
            model_name='bimgrouptype',
            index=models.Index(fields=['display_name'], name='forge_bim_g_display_992b17_idx'),
        ),
        migrations.AddIndex(
            model_name='bimgrouptype',
            index=models.Index(fields=['value'], name='forge_bim_g_value_007d27_idx'),
        ),
        migrations.AddIndex(
            model_name='bimmodel',
            index=models.Index(fields=['name'], name='forge_bim_m_name_a6fce3_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['category'], name='forge_bim_o_categor_7d2372_idx'),
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['conversion'], name='forge_bim_o_convers_faf8e7_idx'),
        ),
    ]
