# Generated by Django 5.1.4 on 2025-06-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0040_bimobject_root_dbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimobject',
            name='numeric_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
