# Generated by Django 5.1.4 on 2025-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0040_bimcategory_forge_bim_c_bim_gro_eefa4d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimconversion',
            index=models.Index(fields=['bim_model', 'version'], name='forge_bim_c_bim_mod_5cba70_idx'),
        ),
    ]
