# Generated by Django 5.1.4 on 2025-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0041_bimobject_numeric_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['numeric_value'], name='forge_bim_o_numeric_55865d_idx'),
        ),
    ]
