# Generated by Django 5.1.4 on 2025-03-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0041_bimconversion_forge_bim_c_bim_mod_5cba70_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bimobject',
            name='forge_bim_o_convers_faf8e7_idx',
        ),
        migrations.RenameIndex(
            model_name='bimgrouptype',
            new_name='forge_bim_t_display_e86d65_idx',
            old_name='forge_bim_g_display_992b17_idx',
        ),
        migrations.RenameIndex(
            model_name='bimgrouptype',
            new_name='forge_bim_t_value_b84de3_idx',
            old_name='forge_bim_g_value_007d27_idx',
        ),
        migrations.RemoveField(
            model_name='bimobject',
            name='conversion',
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimconversion'),
        ),
        migrations.AddIndex(
            model_name='bimcategory',
            index=models.Index(fields=['conversion'], name='forge_bim_c_convers_91c237_idx'),
        ),
        migrations.AlterModelTable(
            name='bimgrouptype',
            table='forge_bim_type',
        ),
    ]
