# Generated by Django 5.1.4 on 2025-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0042_bimobject_forge_bim_o_numeric_55865d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimobject',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['parent_id'], name='forge_bim_o_parent__7c4353_idx'),
        ),
    ]
