# Generated by Django 5.1.4 on 2025-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0042_remove_bimobject_forge_bim_o_convers_faf8e7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimobject',
            name='properties',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('bim_group', 'value', 'conversion')},
        ),
    ]
