# Generated by Django 5.1.4 on 2025-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0043_bimobject_parent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimCobie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'forge_bim_cobie',
                'indexes': [models.Index(fields=['name'], name='forge_bim_c_name_53a06d_idx')],
            },
        ),
    ]
