# Generated by Django 5.1.4 on 2025-04-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0043_bimobject_properties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimobject',
            name='properties',
        ),
        migrations.AddField(
            model_name='bimobject',
            name='display_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
