# Generated by Django 5.1.4 on 2025-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0044_bimcobie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimcobie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
