# Generated by Django 5.1.4 on 2025-04-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0044_remove_bimobject_properties_bimobject_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimobject',
            name='primary_value',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
