# Generated by Django 5.1.4 on 2025-08-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0045_bimcobie_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['display_name', 'value'], name='forge_bim_o_display_db1e96_idx'),
        ),
    ]
