# Generated by Django 5.1.4 on 2025-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0045_bimobject_primary_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['dbid', 'category'], name='forge_bim_o_dbid_59041f_idx'),
        ),
    ]
