# Generated by Django 5.1.4 on 2025-11-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0046_bimobject_forge_bim_o_display_db1e96_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimcobie',
            name='required_status',
            field=models.BooleanField(default=False),
        ),
    ]
