# Generated by Django 5.1.4 on 2025-04-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0046_bimobject_forge_bim_o_dbid_59041f_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bimobject',
            index=models.Index(fields=['dbid'], name='forge_bim_o_dbid_0fbf8a_idx'),
        ),
    ]
