# Generated by Django 5.1.4 on 2025-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0047_bimobject_forge_bim_o_dbid_0fbf8a_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bimconversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bimconversion',
            name='bim_model',
        ),
        migrations.RemoveIndex(
            model_name='bimcategory',
            name='forge_bim_c_convers_91c237_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('bim_group', 'value')},
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='urn',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bimcategory',
            name='conversion',
        ),
        migrations.DeleteModel(
            name='BimConversion',
        ),
    ]
