# Generated by Django 5.1.4 on 2025-11-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0047_bimcobie_required_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimcobie',
            name='example',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='範例'),
        ),
        migrations.AddField(
            model_name='bimcobie',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='bimcobie',
            name='description',
            field=models.CharField(max_length=255, verbose_name='COBie欄位(中文)'),
        ),
        migrations.AlterField(
            model_name='bimcobie',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='COBie欄位(英文)'),
        ),
    ]
