# Generated by Django 5.1.4 on 2025-11-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0048_bimcobie_example_bimcobie_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimobject',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
