# Generated by Django 5.1.4 on 2025-04-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0048_alter_bimconversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimcategory',
            name='bim_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimmodel'),
            preserve_default=False,
        ),
    ]
