# Generated by Django 5.1.4 on 2025-11-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0049_alter_bimobject_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolecode',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='zonecode',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='rolecode',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zonecode',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FileTypeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'forge_file_type_code',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='forge_file__code_8be65e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LevelCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'forge_level_code',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='forge_level_code_b5e99b_idx')],
            },
        ),
    ]
