# Generated by Django 5.1.4 on 2025-04-08 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0049_bimcategory_bim_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bimcategory',
            name='bim_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_categories', to='forge.bimgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='bimcategory',
            unique_together={('bim_model', 'bim_group', 'value')},
        ),
    ]
