# Generated by Django 5.1.4 on 2025-11-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0051_alter_filetypecode_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypecode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='levelcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rolecode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zonecode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
