# Generated by Django 5.2 on 2025-11-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0052_filetypecode_is_active_levelcode_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimcobie',
            name='required_status',
        ),
        migrations.AddField(
            model_name='bimcobie',
            name='status',
            field=models.CharField(choices=[('required', '必填'), ('optional', '選填'), ('auto', '軟體自動代入'), ('undefined', '未定義')], default='undefined', max_length=20, verbose_name='填寫狀態'),
        ),
        migrations.AddIndex(
            model_name='bimcobie',
            index=models.Index(fields=['status'], name='forge_bim_c_status_8f3cff_idx'),
        ),
    ]
