"""
Django settings for tx_bmms project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from django.conf.locale.en import formats as en_formats

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=qxo)i^(3nhpn@=dfdfw^$du=jiayia=955h4gjnqj59do=#bu'
FERNET_SECRET_KEY = "WYX1Lrj2rxHP0zTjdFfZq97GcMlg2A8fDHL5R4JzJYA="

# SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True
DEBUG = os.getenv('DEBUG', 'True') == 'True'

AUTH_USER_MODEL = 'account.User'
ALLOWED_HOSTS = ['*']

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# 設定 PostgreSQL 主機和端口
POSTGRES = {
    'HOST': os.getenv('HOST', 'giantcld.com'),
    'PORT': os.getenv('PORT', 5432),
    'USER': os.getenv('POSTGRESQL_USERNAME', 'bmms'),
    'PASSWORD': os.getenv('POSTGRESQL_PASSWORD', 'qbZucM8vvGwpfTd'),
    'NAME': os.getenv('POSTGRESQL_DATABASE', 'bmms'),
}
# 設定 Redis 主機和端口
REDIS = {
    'HOST': 'localhost' if DEBUG else 'redis',
    'PORT': 6379,
    'DB': 1 if DEBUG else 0
}

# CORS definition
CORS_ALLOW_ALL_ORIGINS = True

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [] if DEBUG else os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')

# Celery
CELERY_BROKER_URL = f'redis://{REDIS["HOST"]}:{REDIS["PORT"]}/{REDIS["DB"]}'
CELERY_RESULT_BACKEND = f'redis://{REDIS["HOST"]}:{REDIS["PORT"]}/{REDIS["DB"]}'
# CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Django channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS['HOST'], REDIS['PORT'])],
        },
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # access token 有效期設為 24 小時
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),   # refresh token 有效期設為 7 天
    'ROTATE_REFRESH_TOKENS': True,                  # 每次使用 refresh token 獲取新 token
    'BLACKLIST_AFTER_ROTATION': True,               # 使用過的 refresh token 被加入黑名單
}

REST_FRAMEWORK = {
    # Simple JWT
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),

    # drf_spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 15,
    # 'DATE_FORMAT': '%Y/%m/%d',
    # 'DATETIME_FORMAT': '%Y/%m/%d %H:%M:%S',
    # 'DATE_INPUT_FORMATS': ['%Y/%m/%d', '%Y/%m/%d %H:%M:%S', ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'BIM Model Management System API',
    'DESCRIPTION': 'Your project description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # OTHER SETTINGS
    'AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
}

INSTALLED_APPS = [
    'daphne',
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'mptt',
    # 'django_celery_results',

    # commands
    'daemon',

    # app
    'apps.account',
    'apps.core',
    'apps.forge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # CORS
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'tx_bmms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tx_bmms.wsgi.application'
ASGI_APPLICATION = 'tx_bmms.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':  POSTGRES['NAME'],
        'USER':  POSTGRES['USER'],
        'PASSWORD': POSTGRES['PASSWORD'],
        'HOST': POSTGRES['HOST'],
        'PORT':  POSTGRES['PORT'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
en_formats.DATETIME_FORMAT = "Y-m-d H:i:s"

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'static-root'

MEDIA_URL = '/backend-media/'
MEDIA_ROOT = BASE_DIR / 'media-root'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

INTERNAL_IPS = ['127.0.0.1']

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
