# Generated by Django 5.1.3 on 2025-12-12 09:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100, unique=True, verbose_name='感測器ID')),
                ('name', models.CharField(max_length=200, verbose_name='名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sensor_type', models.CharField(choices=[('temperature', '溫度'), ('humidity', '濕度'), ('pressure', '壓力'), ('flow', '流量'), ('power', '功率'), ('voltage', '電壓'), ('current', '電流'), ('status', '狀態'), ('occupancy', '佔用率'), ('co2', 'CO2濃度')], max_length=50, verbose_name='類型')),
                ('unit', models.CharField(max_length=20, verbose_name='單位')),
                ('mqtt_topic', models.CharField(blank=True, max_length=255, verbose_name='MQTT Topic')),
                ('mqtt_qos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='QoS等級')),
                ('modbus_address', models.IntegerField(blank=True, null=True, verbose_name='Modbus地址')),
                ('modbus_register', models.IntegerField(blank=True, null=True, verbose_name='Modbus暫存器')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API端點')),
                ('api_method', models.CharField(default='GET', max_length=10, verbose_name='API方法')),
                ('display_format', models.CharField(default='{value} {unit}', max_length=50, verbose_name='顯示格式')),
                ('decimal_places', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='小數位數')),
                ('warning_threshold_min', models.FloatField(blank=True, null=True, verbose_name='警告下限')),
                ('warning_threshold_max', models.FloatField(blank=True, null=True, verbose_name='警告上限')),
                ('error_threshold_min', models.FloatField(blank=True, null=True, verbose_name='錯誤下限')),
                ('error_threshold_max', models.FloatField(blank=True, null=True, verbose_name='錯誤上限')),
                ('data_transform', models.JSONField(blank=True, help_text='{"scale": 1.0, "offset": 0.0}', null=True, verbose_name='數據轉換')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='最後連線時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '感測器',
                'verbose_name_plural': '感測器',
                'db_table': 'sensors',
                'ordering': ['sensor_id'],
            },
        ),
        migrations.CreateModel(
            name='SensorBimBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_urn', models.CharField(max_length=255, verbose_name='模型URN')),
                ('element_dbid', models.IntegerField(verbose_name='元素DbId')),
                ('element_external_id', models.CharField(blank=True, max_length=255, verbose_name='外部ID')),
                ('element_name', models.CharField(blank=True, max_length=255, verbose_name='元素名稱')),
                ('position_type', models.CharField(choices=[('center', '中心'), ('top', '頂部'), ('bottom', '底部'), ('custom', '自訂')], default='center', max_length=20, verbose_name='位置類型')),
                ('position_offset', models.JSONField(blank=True, help_text='{"x": 0, "y": 0, "z": 0}', null=True, verbose_name='位置偏移')),
                ('label_visible', models.BooleanField(default=True, verbose_name='顯示標籤')),
                ('icon_type', models.CharField(blank=True, max_length=50, verbose_name='圖示類型')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='顏色')),
                ('priority', models.IntegerField(default=0, verbose_name='優先順序')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_bindings', to='sensors.sensor', verbose_name='感測器')),
            ],
            options={
                'verbose_name': '感測器BIM綁定',
                'verbose_name_plural': '感測器BIM綁定',
                'db_table': 'sensor_bim_bindings',
                'ordering': ['priority', 'created_at'],
                'unique_together': {('sensor', 'model_urn', 'element_dbid')},
            },
        ),
        migrations.CreateModel(
            name='SensorDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='數值')),
                ('raw_value', models.FloatField(blank=True, null=True, verbose_name='原始數值')),
                ('status', models.CharField(choices=[('normal', '正常'), ('warning', '警告'), ('error', '錯誤'), ('offline', '離線')], default='normal', max_length=20, verbose_name='狀態')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='時間戳')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_logs', to='sensors.sensor', verbose_name='感測器')),
            ],
            options={
                'verbose_name': '感測器數據日誌',
                'verbose_name_plural': '感測器數據日誌',
                'db_table': 'sensor_data_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['sensor_type', 'is_active'], name='sensors_sensor__4e4a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['mqtt_topic'], name='sensors_mqtt_to_88b842_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordatalog',
            index=models.Index(fields=['sensor', '-timestamp'], name='sensor_data_sensor__4f8e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordatalog',
            index=models.Index(fields=['status', '-timestamp'], name='sensor_data_status_a7d8e9_idx'),
        ),
    ]
