# Generated by Django 5.1.4 on 2025-12-20 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorbimbinding',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bim_binding', to='sensors.sensor', verbose_name='感測器'),
        ),
    ]
